# Generated by Django 3.0.3 on 2025-12-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_corpus_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
